kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etcd-cert-signer
subjects:
- kind: ServiceAccount
  name: etcd-cert-signer
roleRef:
  kind: Role
  name: etcd-cert-signer
  apiGroup: rbac.authorization.k8s.io
